title: "Belén Espín"
description: "Audiovisual and Literary Translator | Localization Quality Assurance"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Belén Espín"

navigation:
  - title: "Home"
    url: /
  - title: "Portfolio"
    url: /portfolio/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/
